services:
  accounts:
    image: "hoangquan25/accounts:1.0"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hoangquan
  cards:
    image: "hoangquan25/cards:1.0"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hoangquan
  loans:
    image: "hoangquan25/loans:1.0"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - hoangquan
networks:
  hoangquan:
    driver: "bridge"