spring:
  application:
    name: "configserver"
  profiles:
    active: git
  # active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/hoangQuan25/MyBank-Configserver.git"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "d75c57adede352d03bbfd78a8bd21191 "

server:
  port: 8071