spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.1"

accounts:
  message: "Welcome to HQ banking system related QA APIs"
  contactDetails:
    name: "Hoang Quan - Product owner"
    email: "quanabc@gmail.com"
  onCallSupport:
    - (84) 368 299 999
    - (84) 368 499 999